### ISSUE TITLE
mcrypt removed from PHP 7.2 core

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#10]
**Important: Use [libs-upgrade](https://github.com/magento-engcom/php-7.2-support/tree/libs-upgrade) branch as base for this task and as target for the PR.**

Investigate possible solutions.

Options:
1. use sodium
2. use [mcrypt_compat](https://github.com/phpseclib/mcrypt_compat) lib
3. require PECL installation of mcrypt
4. Other

Design document - https://github.com/magento-engcom/php-7.2-support/wiki/HLD---Removing-mcrypt-and-adding-libsodium

**Comment by buskamuza** [comment]
Note ready for work yet. Requires investigation of which library to use.

**Comment by buskamuza** [comment]
In case of moving to Sodium:
* Couple framework encryption interfaces which should be reimplemented
* `magento/zf1` usages must be adjusted
* A lot of usages in 3rd party libraries, compatible versions existence must be checked

**Comment by giabmf11** [comment]
We have two opitons:
1. Use the mcrypt extension compatible with PHP 7.2 for the next release since it won't require much development time. Mcrypt isn't being maintained anymore so we should integrate a new library at some point but it will take much more time and introduce BC issues. 
2. Use the libsodium bundled extension inherently supported by PHP 7.2 and refactor our code to integrate the new code.

@piotrekkaminski I sent you an email asking your opinion. Let me know if you want to set up a meeting.

**Comment by buskamuza** [comment]
Using mcrypt_compat for 2.3.0.
