### ISSUE TITLE
Update zendframework/zend-code

### ISSUE THREAD

**Issue by buskamuza** [magento-engcom/php-7.2-support#93]
**Important: Use [libs-upgrade](https://github.com/magento-engcom/php-7.2-support/tree/libs-upgrade) branch as base for this task and as target for the PR.**

AC:
- `zendframework/zend-code` is updated to the latest MINOR version (3.3.0)
- the dependency is declared so that MINOR version is fixed (`~3.3.0` instead of `^3.3.0`). Reason: there are differences in behavior between minor versions of this component
- available tests (both internal and Travis CI) are green

**Comment by maxbucknell** [comment]
I am working on this #distributed-cd

**Comment by maxbucknell** [comment]
Seems that most of the issues are related to `zendframework/zend-code` updating to use short array syntax. Since this syntax is used throughout the core, I am updating the tests to use the appropriate array syntax, this fixes the issue.

Will push these when they are finished, which will likely be next week. No other large issues have made themselves visible yet.
